version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: nonuso-api
    ports:
      - "8080:8080"  # HTTP
      - "8081:8081"  # HTTPS / altri usi
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=nonuso;Username=postgres;Password=postgres
   # volumes:
     # - ./src:/app:cached  # opzionale, se vuoi montare codice per hot-reload

  db:
    image: postgres:15
    container_name: nonuso-postgres
    environment:
      POSTGRES_DB: nonuso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
