services:
  webapp:
    build: .
    container_name: nonuso-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=nonuso-postgres;Database=nonuso;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=nonuso-redis:6379,abortConnect=false
    depends_on:
      - postgres
      - redis
    networks:
      - nonuso-network
    restart: unless-stopped

  postgres:
    image: postgis/postgis:16-3.4
    container_name: nonuso-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nonuso
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nonuso-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nonuso-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - nonuso-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  nonuso-network:
    driver: bridge
