services:
  webapp:
    build: .
    container_name: nonuso-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=nonuso;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    depends_on:
      - postgres
      - redis
    networks:
      - nonuso-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: nonuso-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nonuso
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nonuso-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nonuso-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - nonuso-network
    restart: unless-stopped
  
  migration:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app
    volumes:
      - ./publish:/app
    networks:
      - nonuso-network
    entrypoint: []
    command: >
      dotnet tool install --global dotnet-ef --version 9.0.0 &&
      export PATH="$PATH:/root/.dotnet/tools" &&
      dotnet ef database update
      --project ./Nonuso.Infrastructure.Persistence/Nonuso.Infrastructure.Persistence.csproj
      --startup-project ./Api/Nonuso.Api.csproj

volumes:
  postgres-data:
  redis-data:

networks:
  nonuso-network:
    driver: bridge